// Starter exercise library. A small, hand-written set proving the model;
// expand toward a full catalog before launch.
import type { Exercise } from './types';

export const SEED_EXERCISES: Exercise[] = [
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'push',
    description: 'The classic horizontal press for chest, shoulders, and triceps.',
    cues: [
      'Plant the feet and keep a slight arch in the upper back.',
      'Lower the bar to the mid-chest with elbows ~45°.',
      'Drive up and slightly back toward the rack.',
    ],
    primaryMuscles: ['Chest', 'Triceps', 'Front delts'],
    equipment: 'Barbell + bench',
    difficulty: 3,
    level: 'Intermediate',
    defaultSets: 4,
    defaultReps: 8,
    defaultRestSeconds: 120,
    referenceUrl: null,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'push',
    description: 'Standing barbell press overhead — builds shoulders and lockout strength.',
    cues: ['Brace the core and squeeze the glutes.', 'Press the bar in a straight line, head through at the top.'],
    primaryMuscles: ['Shoulders', 'Triceps'],
    equipment: 'Barbell',
    difficulty: 3,
    level: 'Intermediate',
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 120,
    referenceUrl: null,
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'push',
    description: 'Bodyweight horizontal press. Scales from knees to weighted.',
    cues: ['Keep a straight line from head to heels.', 'Lower until the chest is just above the floor.'],
    primaryMuscles: ['Chest', 'Triceps', 'Core'],
    equipment: 'Bodyweight',
    difficulty: 1,
    level: 'Beginner',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSeconds: 60,
    referenceUrl: null,
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'pull',
    description: 'Vertical pull from a bar — the benchmark upper-back exercise.',
    cues: ['Start from a dead hang.', 'Drive the elbows down and back; chin over the bar.'],
    primaryMuscles: ['Lats', 'Biceps', 'Upper back'],
    equipment: 'Pull-up bar',
    difficulty: 3,
    level: 'Intermediate',
    defaultSets: 4,
    defaultReps: 6,
    defaultRestSeconds: 120,
    referenceUrl: null,
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'pull',
    description: 'Bent-over horizontal pull for the mid-back and lats.',
    cues: ['Hinge to ~45°, flat back.', 'Pull to the lower ribs, squeeze the shoulder blades.'],
    primaryMuscles: ['Lats', 'Mid-back', 'Biceps'],
    equipment: 'Barbell',
    difficulty: 2,
    level: 'Intermediate',
    defaultSets: 4,
    defaultReps: 10,
    defaultRestSeconds: 90,
    referenceUrl: null,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'pull',
    description: 'Cable vertical pull — a scalable pull-up alternative.',
    cues: ['Lead with the elbows.', 'Control the bar back up; no swinging.'],
    primaryMuscles: ['Lats', 'Biceps'],
    equipment: 'Cable machine',
    difficulty: 1,
    level: 'Beginner',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSeconds: 75,
    referenceUrl: null,
  },
  {
    id: 'back-squat',
    name: 'Back Squat',
    category: 'legs',
    description: 'The foundational barbell squat for total lower-body strength.',
    cues: ['Brace, break at the hips and knees together.', 'Knees track over the toes; depth to parallel or below.'],
    primaryMuscles: ['Quads', 'Glutes', 'Core'],
    equipment: 'Barbell + rack',
    difficulty: 4,
    level: 'Intermediate',
    defaultSets: 4,
    defaultReps: 6,
    defaultRestSeconds: 150,
    referenceUrl: null,
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'pull',
    description: 'Hip hinge pulling the bar from the floor — full posterior chain.',
    cues: ['Bar over mid-foot, flat back, brace hard.', 'Push the floor away; lock out with the glutes.'],
    primaryMuscles: ['Hamstrings', 'Glutes', 'Back'],
    equipment: 'Barbell',
    difficulty: 4,
    level: 'Advanced',
    defaultSets: 3,
    defaultReps: 5,
    defaultRestSeconds: 180,
    referenceUrl: null,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    description: 'A hip-hinge focused on hamstrings and glutes with a soft knee.',
    cues: ['Push the hips back, bar close to the legs.', 'Feel the hamstring stretch; stand tall to finish.'],
    primaryMuscles: ['Hamstrings', 'Glutes'],
    equipment: 'Barbell',
    difficulty: 3,
    level: 'Intermediate',
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 90,
    referenceUrl: null,
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'legs',
    description: 'Alternating forward lunges — unilateral leg strength and balance.',
    cues: ['Long step, drop the back knee toward the floor.', 'Push through the front heel to stand.'],
    primaryMuscles: ['Quads', 'Glutes'],
    equipment: 'Dumbbells (optional)',
    difficulty: 2,
    level: 'Beginner',
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSeconds: 75,
    referenceUrl: null,
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    description: 'Isometric core hold. Log reps as seconds held.',
    cues: ['Straight line head to heels.', 'Squeeze glutes and brace; don’t let the hips sag.'],
    primaryMuscles: ['Core', 'Shoulders'],
    equipment: 'Bodyweight',
    difficulty: 1,
    level: 'Beginner',
    defaultSets: 3,
    defaultReps: 45,
    defaultRestSeconds: 45,
    referenceUrl: null,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'core',
    description: 'Hang from a bar and raise the legs — lower-ab and grip work.',
    cues: ['Avoid swinging; control up and down.', 'Posterior tilt at the top.'],
    primaryMuscles: ['Core', 'Hip flexors'],
    equipment: 'Pull-up bar',
    difficulty: 3,
    level: 'Intermediate',
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 60,
    referenceUrl: null,
  },
];

export function getExercise(id: string): Exercise | undefined {
  return SEED_EXERCISES.find((e) => e.id === id);
}
