// Starter asana library. Mirrors lib/data/seedSkills.ts in spirit: a small,
// hand-written seed set that proves the model end-to-end. Expand toward the
// 280+ poses that leading apps ship before launch.
import type { Asana } from './types';

export const SEED_ASANAS: Asana[] = [
  {
    id: 'mountain',
    name: 'Mountain Pose',
    sanskritName: 'Tadasana',
    category: 'standing',
    description:
      'The foundational standing pose. You stand tall and grounded, the blueprint for alignment in every other standing posture.',
    benefits: ['Improves posture', 'Builds body awareness', 'Grounds and centers'],
    cues: [
      'Spread your toes and root down through all four corners of the feet.',
      'Stack ankles, hips, shoulders and ears in one line.',
      'Relax the shoulders down and away from the ears.',
    ],
    focus: ['Posture', 'Grounding', 'Breath'],
    difficulty: 1,
    level: 'Beginner',
    defaultHoldSeconds: 30,
    contraindications: ['Low blood pressure (rise slowly)'],
    referenceUrl: 'https://www.youtube.com/watch?v=ATLU-XX_lro',
  },
  {
    id: 'downward-dog',
    name: 'Downward-Facing Dog',
    sanskritName: 'Adho Mukha Svanasana',
    category: 'standing',
    description:
      'An inverted V shape and one of the most recognizable poses. A full-body stretch that also builds upper-body strength.',
    benefits: ['Lengthens hamstrings and calves', 'Strengthens arms and shoulders', 'Energizes the body'],
    cues: [
      'Press the floor away through the hands; spread the fingers wide.',
      'Lift the hips up and back toward the ceiling.',
      'Let the heels reach toward the floor — they need not touch.',
    ],
    focus: ['Hamstrings', 'Shoulders', 'Core'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 45,
    contraindications: ['Wrist injury', 'Late-term pregnancy'],
    referenceUrl: 'https://www.youtube.com/watch?v=EYuJRSf0JaM',
  },
  {
    id: 'warrior-1',
    name: 'Warrior I',
    sanskritName: 'Virabhadrasana I',
    category: 'standing',
    description:
      'A strong standing lunge with the arms overhead. Builds lower-body strength and opens the front body.',
    benefits: ['Strengthens legs and glutes', 'Opens hips and chest', 'Builds stamina'],
    cues: [
      'Bend the front knee over the ankle, not past the toes.',
      'Ground the back heel down at a 45-degree angle.',
      'Reach the arms up while drawing the lower ribs in.',
    ],
    focus: ['Quads', 'Glutes', 'Hip flexors'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 30,
    contraindications: ['Knee injury', 'High blood pressure (lower arms)'],
    referenceUrl: 'https://www.youtube.com/watch?v=k4qaVoAbeHM',
  },
  {
    id: 'warrior-2',
    name: 'Warrior II',
    sanskritName: 'Virabhadrasana II',
    category: 'standing',
    description:
      'A grounded standing pose with arms extended front and back, gaze over the front hand. Builds focus and leg strength.',
    benefits: ['Strengthens legs', 'Opens hips', 'Improves concentration'],
    cues: [
      'Stack the front knee directly over the ankle.',
      'Reach actively through both fingertips, shoulders relaxed.',
      'Sink the hips while keeping the torso upright and centered.',
    ],
    focus: ['Quads', 'Hips', 'Shoulders'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 30,
    contraindications: ['Knee injury', 'Hip injury'],
    referenceUrl: 'https://www.youtube.com/watch?v=hmZxKCXS0tY',
  },
  {
    id: 'tree',
    name: 'Tree Pose',
    sanskritName: 'Vrksasana',
    category: 'balance',
    description:
      'A single-leg balancing pose with the sole of one foot pressed into the standing leg. Builds focus and stability.',
    benefits: ['Improves balance', 'Strengthens ankles and calves', 'Sharpens focus'],
    cues: [
      'Press the foot and leg into each other to create stability.',
      'Avoid placing the foot directly on the knee.',
      'Fix your gaze on one steady point (drishti).',
    ],
    focus: ['Balance', 'Ankles', 'Focus'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 30,
    contraindications: ['Low blood pressure', 'Acute ankle injury'],
    referenceUrl: 'https://www.youtube.com/watch?v=wdln9qWYloU',
  },
  {
    id: 'chair',
    name: 'Chair Pose',
    sanskritName: 'Utkatasana',
    category: 'standing',
    description:
      'A powerful pose like sitting back into an invisible chair, arms reaching up. Builds heat and leg strength.',
    benefits: ['Strengthens thighs and glutes', 'Builds heat', 'Tones core'],
    cues: [
      'Sit the hips back and down as if reaching for a chair.',
      'Keep weight in the heels; you should see your toes.',
      'Lengthen the tailbone down to protect the lower back.',
    ],
    focus: ['Quads', 'Glutes', 'Core'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 30,
    contraindications: ['Knee injury', 'Low blood pressure'],
    referenceUrl: 'https://www.youtube.com/watch?v=ZDPMdCSy4jQ',
  },
  {
    id: 'cobra',
    name: 'Cobra Pose',
    sanskritName: 'Bhujangasana',
    category: 'backbend',
    description:
      'A gentle backbend from lying prone, lifting the chest with the hands beside the ribs. Opens the front body.',
    benefits: ['Strengthens the spine', 'Opens chest and shoulders', 'Counters slouching'],
    cues: [
      'Press the tops of the feet and pelvis into the floor.',
      'Lift the chest using back strength, not just the arms.',
      'Keep the shoulders sliding down, away from the ears.',
    ],
    focus: ['Spine', 'Chest', 'Posture'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 20,
    contraindications: ['Back injury', 'Pregnancy', 'Carpal tunnel syndrome'],
    referenceUrl: 'https://www.youtube.com/watch?v=FCEhHyu7H_w',
  },
  {
    id: 'childs-pose',
    name: "Child's Pose",
    sanskritName: 'Balasana',
    category: 'restorative',
    description:
      'A resting pose, kneeling with the torso folded forward and arms extended or alongside the body. A reset between efforts.',
    benefits: ['Calms the nervous system', 'Gently stretches hips and back', 'Relieves fatigue'],
    cues: [
      'Bring the big toes together and knees as wide as is comfortable.',
      'Rest the forehead on the mat or a block.',
      'Breathe into the back of the ribs.',
    ],
    focus: ['Rest', 'Lower back', 'Hips'],
    difficulty: 1,
    level: 'Beginner',
    defaultHoldSeconds: 60,
    contraindications: ['Knee injury', 'Pregnancy (knees wide)'],
    referenceUrl: 'https://www.youtube.com/watch?v=l-mtV34Afok',
  },
  {
    id: 'seated-forward-fold',
    name: 'Seated Forward Fold',
    sanskritName: 'Paschimottanasana',
    category: 'forward-fold',
    description:
      'A seated fold over straight legs. A deep stretch for the entire back body and a quieting, introspective pose.',
    benefits: ['Stretches hamstrings and spine', 'Calms the mind', 'Aids digestion'],
    cues: [
      'Hinge from the hips, not the waist; lead with the chest.',
      'Keep a micro-bend in the knees if the hamstrings are tight.',
      'Lengthen the spine on each inhale, fold on each exhale.',
    ],
    focus: ['Hamstrings', 'Spine', 'Calm'],
    difficulty: 2,
    level: 'Intermediate',
    defaultHoldSeconds: 45,
    contraindications: ['Lower-back injury', 'Sciatica'],
    referenceUrl: 'https://www.youtube.com/watch?v=4VLYUCml5sw',
  },
  {
    id: 'bridge',
    name: 'Bridge Pose',
    sanskritName: 'Setu Bandha Sarvangasana',
    category: 'backbend',
    description:
      'A supported backbend lifting the hips from a lying position. Opens the front body and strengthens the back chain.',
    benefits: ['Strengthens glutes and hamstrings', 'Opens chest', 'Gentle energizer'],
    cues: [
      'Press through the feet to lift the hips.',
      'Keep the knees hip-width — avoid letting them splay out.',
      'Roll the shoulders under and clasp the hands if accessible.',
    ],
    focus: ['Glutes', 'Spine', 'Chest'],
    difficulty: 2,
    level: 'Beginner',
    defaultHoldSeconds: 30,
    contraindications: ['Neck injury'],
    referenceUrl: 'https://www.youtube.com/watch?v=6HYNo1YQsUk',
  },
  {
    id: 'twist-supine',
    name: 'Supine Spinal Twist',
    sanskritName: 'Supta Matsyendrasana',
    category: 'twist',
    description:
      'A reclined twist that wrings out the spine. A gentle, releasing pose often used near the end of practice.',
    benefits: ['Releases the lower back', 'Improves spinal mobility', 'Aids relaxation'],
    cues: [
      'Drop both knees to one side, gaze the opposite way.',
      'Keep both shoulders grounded on the mat.',
      'Let gravity do the work — no forcing.',
    ],
    focus: ['Spine', 'Lower back', 'Release'],
    difficulty: 1,
    level: 'Beginner',
    defaultHoldSeconds: 45,
    contraindications: ['Recent abdominal or spinal surgery'],
    referenceUrl: 'https://www.youtube.com/watch?v=ezyMaQEaVaI',
  },
  {
    id: 'corpse',
    name: 'Corpse Pose',
    sanskritName: 'Savasana',
    category: 'restorative',
    description:
      'The final resting pose: lying flat, completely still, integrating the practice. Deceptively simple, deeply important.',
    benefits: ['Deep relaxation', 'Integrates the practice', 'Lowers stress'],
    cues: [
      'Let the feet fall open and the palms face up.',
      'Soften the jaw, the eyes, and the breath.',
      'Stay for at least a few minutes; resist the urge to rush off.',
    ],
    focus: ['Rest', 'Breath', 'Stillness'],
    difficulty: 1,
    level: 'Beginner',
    defaultHoldSeconds: 120,
    contraindications: ['Late-term pregnancy (lie on side instead)'],
    referenceUrl: 'https://www.youtube.com/watch?v=ocnRmfbFV9E',
  },
];

export function getAsana(id: string): Asana | undefined {
  return SEED_ASANAS.find((a) => a.id === id);
}
